version: '3.9'
services:
  app:
    image: python-dogsvet-user:0.0.1
    tty: true
    environment:
      # Main file
      - FLASK_APP=main
      # Develpment mode
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_DEBUG=True
      - FLASK_RUN_PORT=5000
    # tty: true
    entrypoint: [ "flask", "run" ]
    ports:
      - 5000:5000
    build:
      context: .
    volumes:
      - ./src:/opt/user/src
