name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r src/requirements.txt

#    - name: Analysing the code with pylint
#      run: |
#        pylint $(git ls-files '*.py')
    - name: Build docker image
      run: |
        docker-compose build

#    - name: Start all services
#      run: |
#        docker-compose up -d

    - name: Run Python Test
      run: |
        docker-compose run --entrypoint "/usr/local/bin/python tests/test_create_user.py" app